//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryDataStockItemExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryDataStockItemInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int itemIdField;
        
        private bool itemIdFieldSpecified;
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private int stockIdField;
        
        private bool stockIdFieldSpecified;
        
        private string qtyField;
        
        private bool isInStockField;
        
        private bool isQtyDecimalField;
        
        private bool showDefaultNotificationMessageField;
        
        private bool useConfigMinQtyField;
        
        private float minQtyField;
        
        private int useConfigMinSaleQtyField;
        
        private float minSaleQtyField;
        
        private bool useConfigMaxSaleQtyField;
        
        private float maxSaleQtyField;
        
        private bool useConfigBackordersField;
        
        private int backordersField;
        
        private bool useConfigNotifyStockQtyField;
        
        private float notifyStockQtyField;
        
        private bool useConfigQtyIncrementsField;
        
        private float qtyIncrementsField;
        
        private bool useConfigEnableQtyIncField;
        
        private bool enableQtyIncrementsField;
        
        private bool useConfigManageStockField;
        
        private bool manageStockField;
        
        private string lowStockDateField;
        
        private bool isDecimalDividedField;
        
        private int stockStatusChangedAutoField;
        
        private CatalogInventoryDataStockItemExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int itemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("itemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemIdSpecified {
            get {
                return this.itemIdFieldSpecified;
            }
            set {
                this.itemIdFieldSpecified = value;
                this.RaisePropertyChanged("itemIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int stockId {
            get {
                return this.stockIdField;
            }
            set {
                this.stockIdField = value;
                this.RaisePropertyChanged("stockId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockIdSpecified {
            get {
                return this.stockIdFieldSpecified;
            }
            set {
                this.stockIdFieldSpecified = value;
                this.RaisePropertyChanged("stockIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isInStock {
            get {
                return this.isInStockField;
            }
            set {
                this.isInStockField = value;
                this.RaisePropertyChanged("isInStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool isQtyDecimal {
            get {
                return this.isQtyDecimalField;
            }
            set {
                this.isQtyDecimalField = value;
                this.RaisePropertyChanged("isQtyDecimal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool showDefaultNotificationMessage {
            get {
                return this.showDefaultNotificationMessageField;
            }
            set {
                this.showDefaultNotificationMessageField = value;
                this.RaisePropertyChanged("showDefaultNotificationMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool useConfigMinQty {
            get {
                return this.useConfigMinQtyField;
            }
            set {
                this.useConfigMinQtyField = value;
                this.RaisePropertyChanged("useConfigMinQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float minQty {
            get {
                return this.minQtyField;
            }
            set {
                this.minQtyField = value;
                this.RaisePropertyChanged("minQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int useConfigMinSaleQty {
            get {
                return this.useConfigMinSaleQtyField;
            }
            set {
                this.useConfigMinSaleQtyField = value;
                this.RaisePropertyChanged("useConfigMinSaleQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public float minSaleQty {
            get {
                return this.minSaleQtyField;
            }
            set {
                this.minSaleQtyField = value;
                this.RaisePropertyChanged("minSaleQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool useConfigMaxSaleQty {
            get {
                return this.useConfigMaxSaleQtyField;
            }
            set {
                this.useConfigMaxSaleQtyField = value;
                this.RaisePropertyChanged("useConfigMaxSaleQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public float maxSaleQty {
            get {
                return this.maxSaleQtyField;
            }
            set {
                this.maxSaleQtyField = value;
                this.RaisePropertyChanged("maxSaleQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool useConfigBackorders {
            get {
                return this.useConfigBackordersField;
            }
            set {
                this.useConfigBackordersField = value;
                this.RaisePropertyChanged("useConfigBackorders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int backorders {
            get {
                return this.backordersField;
            }
            set {
                this.backordersField = value;
                this.RaisePropertyChanged("backorders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public bool useConfigNotifyStockQty {
            get {
                return this.useConfigNotifyStockQtyField;
            }
            set {
                this.useConfigNotifyStockQtyField = value;
                this.RaisePropertyChanged("useConfigNotifyStockQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public float notifyStockQty {
            get {
                return this.notifyStockQtyField;
            }
            set {
                this.notifyStockQtyField = value;
                this.RaisePropertyChanged("notifyStockQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool useConfigQtyIncrements {
            get {
                return this.useConfigQtyIncrementsField;
            }
            set {
                this.useConfigQtyIncrementsField = value;
                this.RaisePropertyChanged("useConfigQtyIncrements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public float qtyIncrements {
            get {
                return this.qtyIncrementsField;
            }
            set {
                this.qtyIncrementsField = value;
                this.RaisePropertyChanged("qtyIncrements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public bool useConfigEnableQtyInc {
            get {
                return this.useConfigEnableQtyIncField;
            }
            set {
                this.useConfigEnableQtyIncField = value;
                this.RaisePropertyChanged("useConfigEnableQtyInc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public bool enableQtyIncrements {
            get {
                return this.enableQtyIncrementsField;
            }
            set {
                this.enableQtyIncrementsField = value;
                this.RaisePropertyChanged("enableQtyIncrements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public bool useConfigManageStock {
            get {
                return this.useConfigManageStockField;
            }
            set {
                this.useConfigManageStockField = value;
                this.RaisePropertyChanged("useConfigManageStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public bool manageStock {
            get {
                return this.manageStockField;
            }
            set {
                this.manageStockField = value;
                this.RaisePropertyChanged("manageStock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string lowStockDate {
            get {
                return this.lowStockDateField;
            }
            set {
                this.lowStockDateField = value;
                this.RaisePropertyChanged("lowStockDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public bool isDecimalDivided {
            get {
                return this.isDecimalDividedField;
            }
            set {
                this.isDecimalDividedField = value;
                this.RaisePropertyChanged("isDecimalDivided");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int stockStatusChangedAuto {
            get {
                return this.stockStatusChangedAutoField;
            }
            set {
                this.stockStatusChangedAutoField = value;
                this.RaisePropertyChanged("stockStatusChangedAuto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public CatalogInventoryDataStockItemExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1GetStockItemBySkuResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogInventoryDataStockItemInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CatalogInventoryDataStockItemInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1GetStockItemBySkuRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productSkuField;
        
        private int scopeIdField;
        
        private bool scopeIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string productSku {
            get {
                return this.productSkuField;
            }
            set {
                this.productSkuField = value;
                this.RaisePropertyChanged("productSku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int scopeId {
            get {
                return this.scopeIdField;
            }
            set {
                this.scopeIdField = value;
                this.RaisePropertyChanged("scopeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scopeIdSpecified {
            get {
                return this.scopeIdFieldSpecified;
            }
            set {
                this.scopeIdFieldSpecified = value;
                this.RaisePropertyChanged("scopeIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1", ConfigurationName="Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistr" +
        "yV1PortType")]
    public interface catalogInventoryStockRegistryV1PortType {
        
        // CODEGEN: Generating message contract since the operation catalogInventoryStockRegistryV1GetStockItemBySku is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1GetStockItemBySku", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.GenericFault), Action="catalogInventoryStockRegistryV1GetStockItemBySku", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuResponse1 catalogInventoryStockRegistryV1GetStockItemBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1GetStockItemBySku", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuResponse1> catalogInventoryStockRegistryV1GetStockItemBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogInventoryStockRegistryV1UpdateStockItemBySku is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1UpdateStockItemBySku", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.GenericFault), Action="catalogInventoryStockRegistryV1UpdateStockItemBySku", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1 catalogInventoryStockRegistryV1UpdateStockItemBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1UpdateStockItemBySku", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1> catalogInventoryStockRegistryV1UpdateStockItemBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogInventoryStockRegistryV1GetLowStockItems is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1GetLowStockItems", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.GenericFault), Action="catalogInventoryStockRegistryV1GetLowStockItems", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsResponse1 catalogInventoryStockRegistryV1GetLowStockItems(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1GetLowStockItems", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsResponse1> catalogInventoryStockRegistryV1GetLowStockItemsAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogInventoryStockRegistryV1GetStockStatusBySku is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1GetStockStatusBySku", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.GenericFault), Action="catalogInventoryStockRegistryV1GetStockStatusBySku", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1 catalogInventoryStockRegistryV1GetStockStatusBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogInventoryStockRegistryV1GetStockStatusBySku", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1> catalogInventoryStockRegistryV1GetStockStatusBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1GetStockItemBySkuRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockItemBySkuRequest catalogInventoryStockRegistryV1GetStockItemBySkuRequest;
        
        public catalogInventoryStockRegistryV1GetStockItemBySkuRequest1() {
        }
        
        public catalogInventoryStockRegistryV1GetStockItemBySkuRequest1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockItemBySkuRequest catalogInventoryStockRegistryV1GetStockItemBySkuRequest) {
            this.catalogInventoryStockRegistryV1GetStockItemBySkuRequest = catalogInventoryStockRegistryV1GetStockItemBySkuRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1GetStockItemBySkuResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockItemBySkuResponse catalogInventoryStockRegistryV1GetStockItemBySkuResponse;
        
        public catalogInventoryStockRegistryV1GetStockItemBySkuResponse1() {
        }
        
        public catalogInventoryStockRegistryV1GetStockItemBySkuResponse1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockItemBySkuResponse catalogInventoryStockRegistryV1GetStockItemBySkuResponse) {
            this.catalogInventoryStockRegistryV1GetStockItemBySkuResponse = catalogInventoryStockRegistryV1GetStockItemBySkuResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1UpdateStockItemBySkuRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productSkuField;
        
        private CatalogInventoryDataStockItemInterface stockItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string productSku {
            get {
                return this.productSkuField;
            }
            set {
                this.productSkuField = value;
                this.RaisePropertyChanged("productSku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CatalogInventoryDataStockItemInterface stockItem {
            get {
                return this.stockItemField;
            }
            set {
                this.stockItemField = value;
                this.RaisePropertyChanged("stockItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1UpdateStockItemBySkuResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1UpdateStockItemBySkuRequest catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest;
        
        public catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1() {
        }
        
        public catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1UpdateStockItemBySkuRequest catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest) {
            this.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest = catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1UpdateStockItemBySkuResponse catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse;
        
        public catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1() {
        }
        
        public catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1UpdateStockItemBySkuResponse catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse) {
            this.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse = catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1GetLowStockItemsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int scopeIdField;
        
        private float qtyField;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int scopeId {
            get {
                return this.scopeIdField;
            }
            set {
                this.scopeIdField = value;
                this.RaisePropertyChanged("scopeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
                this.RaisePropertyChanged("currentPage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified {
            get {
                return this.currentPageFieldSpecified;
            }
            set {
                this.currentPageFieldSpecified = value;
                this.RaisePropertyChanged("currentPageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
                this.RaisePropertyChanged("pageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified {
            get {
                return this.pageSizeFieldSpecified;
            }
            set {
                this.pageSizeFieldSpecified = value;
                this.RaisePropertyChanged("pageSizeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1GetLowStockItemsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogInventoryDataStockStatusCollectionInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CatalogInventoryDataStockStatusCollectionInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryDataStockStatusCollectionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogInventoryDataStockStatusInterface[] itemsField;
        
        private CatalogInventoryStockStatusCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CatalogInventoryDataStockStatusInterface[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CatalogInventoryStockStatusCriteriaInterface searchCriteria {
            get {
                return this.searchCriteriaField;
            }
            set {
                this.searchCriteriaField = value;
                this.RaisePropertyChanged("searchCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("totalCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryDataStockStatusInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int productIdField;
        
        private int stockIdField;
        
        private int qtyField;
        
        private int stockStatusField;
        
        private CatalogInventoryDataStockItemInterface stockItemField;
        
        private CatalogInventoryDataStockStatusExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int stockId {
            get {
                return this.stockIdField;
            }
            set {
                this.stockIdField = value;
                this.RaisePropertyChanged("stockId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stockStatus {
            get {
                return this.stockStatusField;
            }
            set {
                this.stockStatusField = value;
                this.RaisePropertyChanged("stockStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public CatalogInventoryDataStockItemInterface stockItem {
            get {
                return this.stockItemField;
            }
            set {
                this.stockItemField = value;
                this.RaisePropertyChanged("stockItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public CatalogInventoryDataStockStatusExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryDataStockStatusExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockStatusCriteriaInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mapperInterfaceNameField;
        
        private FrameworkCriteriaInterface[] criteriaListField;
        
        private string[] filtersField;
        
        private string[] ordersField;
        
        private string[] limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mapperInterfaceName {
            get {
                return this.mapperInterfaceNameField;
            }
            set {
                this.mapperInterfaceNameField = value;
                this.RaisePropertyChanged("mapperInterfaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkCriteriaInterface[] criteriaList {
            get {
                return this.criteriaListField;
            }
            set {
                this.criteriaListField = value;
                this.RaisePropertyChanged("criteriaList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
                this.RaisePropertyChanged("filters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
                this.RaisePropertyChanged("orders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class FrameworkCriteriaInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mapperInterfaceNameField;
        
        private FrameworkCriteriaInterface[] criteriaListField;
        
        private string[] filtersField;
        
        private string[] ordersField;
        
        private string[] limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mapperInterfaceName {
            get {
                return this.mapperInterfaceNameField;
            }
            set {
                this.mapperInterfaceNameField = value;
                this.RaisePropertyChanged("mapperInterfaceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkCriteriaInterface[] criteriaList {
            get {
                return this.criteriaListField;
            }
            set {
                this.criteriaListField = value;
                this.RaisePropertyChanged("criteriaList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
                this.RaisePropertyChanged("filters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
                this.RaisePropertyChanged("orders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1GetLowStockItemsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetLowStockItemsRequest catalogInventoryStockRegistryV1GetLowStockItemsRequest;
        
        public catalogInventoryStockRegistryV1GetLowStockItemsRequest1() {
        }
        
        public catalogInventoryStockRegistryV1GetLowStockItemsRequest1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetLowStockItemsRequest catalogInventoryStockRegistryV1GetLowStockItemsRequest) {
            this.catalogInventoryStockRegistryV1GetLowStockItemsRequest = catalogInventoryStockRegistryV1GetLowStockItemsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1GetLowStockItemsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetLowStockItemsResponse catalogInventoryStockRegistryV1GetLowStockItemsResponse;
        
        public catalogInventoryStockRegistryV1GetLowStockItemsResponse1() {
        }
        
        public catalogInventoryStockRegistryV1GetLowStockItemsResponse1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetLowStockItemsResponse catalogInventoryStockRegistryV1GetLowStockItemsResponse) {
            this.catalogInventoryStockRegistryV1GetLowStockItemsResponse = catalogInventoryStockRegistryV1GetLowStockItemsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1GetStockStatusBySkuRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productSkuField;
        
        private int scopeIdField;
        
        private bool scopeIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string productSku {
            get {
                return this.productSkuField;
            }
            set {
                this.productSkuField = value;
                this.RaisePropertyChanged("productSku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int scopeId {
            get {
                return this.scopeIdField;
            }
            set {
                this.scopeIdField = value;
                this.RaisePropertyChanged("scopeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scopeIdSpecified {
            get {
                return this.scopeIdFieldSpecified;
            }
            set {
                this.scopeIdFieldSpecified = value;
                this.RaisePropertyChanged("scopeIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
        "ryStockRegistryV1")]
    public partial class CatalogInventoryStockRegistryV1GetStockStatusBySkuResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogInventoryDataStockStatusInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CatalogInventoryDataStockStatusInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockStatusBySkuRequest catalogInventoryStockRegistryV1GetStockStatusBySkuRequest;
        
        public catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1() {
        }
        
        public catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockStatusBySkuRequest catalogInventoryStockRegistryV1GetStockStatusBySkuRequest) {
            this.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest = catalogInventoryStockRegistryV1GetStockStatusBySkuRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://199.48.164.39:4423/Magento-2-0-2-0-ce/soap/default?services=catalogInvento" +
            "ryStockRegistryV1", Order=0)]
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockStatusBySkuResponse catalogInventoryStockRegistryV1GetStockStatusBySkuResponse;
        
        public catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1() {
        }
        
        public catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockStatusBySkuResponse catalogInventoryStockRegistryV1GetStockStatusBySkuResponse) {
            this.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse = catalogInventoryStockRegistryV1GetStockStatusBySkuResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface catalogInventoryStockRegistryV1PortTypeChannel : MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class catalogInventoryStockRegistryV1PortTypeClient : System.ServiceModel.ClientBase<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType>, MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType {
        
        public catalogInventoryStockRegistryV1PortTypeClient() {
        }
        
        public catalogInventoryStockRegistryV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public catalogInventoryStockRegistryV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogInventoryStockRegistryV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogInventoryStockRegistryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuResponse1 MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1GetStockItemBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1GetStockItemBySku(request);
        }
        
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockItemBySkuResponse catalogInventoryStockRegistryV1GetStockItemBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockItemBySkuRequest catalogInventoryStockRegistryV1GetStockItemBySkuRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1();
            inValue.catalogInventoryStockRegistryV1GetStockItemBySkuRequest = catalogInventoryStockRegistryV1GetStockItemBySkuRequest;
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuResponse1 retVal = ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1GetStockItemBySku(inValue);
            return retVal.catalogInventoryStockRegistryV1GetStockItemBySkuResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuResponse1> MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1GetStockItemBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1GetStockItemBySkuAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuResponse1> catalogInventoryStockRegistryV1GetStockItemBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockItemBySkuRequest catalogInventoryStockRegistryV1GetStockItemBySkuRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockItemBySkuRequest1();
            inValue.catalogInventoryStockRegistryV1GetStockItemBySkuRequest = catalogInventoryStockRegistryV1GetStockItemBySkuRequest;
            return ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1GetStockItemBySkuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1 MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1UpdateStockItemBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1UpdateStockItemBySku(request);
        }
        
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1UpdateStockItemBySkuResponse catalogInventoryStockRegistryV1UpdateStockItemBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1UpdateStockItemBySkuRequest catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1();
            inValue.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest = catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest;
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1 retVal = ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1UpdateStockItemBySku(inValue);
            return retVal.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1> MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1UpdateStockItemBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1UpdateStockItemBySkuAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuResponse1> catalogInventoryStockRegistryV1UpdateStockItemBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1UpdateStockItemBySkuRequest catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest1();
            inValue.catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest = catalogInventoryStockRegistryV1UpdateStockItemBySkuRequest;
            return ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1UpdateStockItemBySkuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsResponse1 MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1GetLowStockItems(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1GetLowStockItems(request);
        }
        
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetLowStockItemsResponse catalogInventoryStockRegistryV1GetLowStockItems(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetLowStockItemsRequest catalogInventoryStockRegistryV1GetLowStockItemsRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1();
            inValue.catalogInventoryStockRegistryV1GetLowStockItemsRequest = catalogInventoryStockRegistryV1GetLowStockItemsRequest;
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsResponse1 retVal = ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1GetLowStockItems(inValue);
            return retVal.catalogInventoryStockRegistryV1GetLowStockItemsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsResponse1> MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1GetLowStockItemsAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1GetLowStockItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsResponse1> catalogInventoryStockRegistryV1GetLowStockItemsAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetLowStockItemsRequest catalogInventoryStockRegistryV1GetLowStockItemsRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetLowStockItemsRequest1();
            inValue.catalogInventoryStockRegistryV1GetLowStockItemsRequest = catalogInventoryStockRegistryV1GetLowStockItemsRequest;
            return ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1GetLowStockItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1 MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1GetStockStatusBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1GetStockStatusBySku(request);
        }
        
        public MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockStatusBySkuResponse catalogInventoryStockRegistryV1GetStockStatusBySku(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockStatusBySkuRequest catalogInventoryStockRegistryV1GetStockStatusBySkuRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1();
            inValue.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest = catalogInventoryStockRegistryV1GetStockStatusBySkuRequest;
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1 retVal = ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1GetStockStatusBySku(inValue);
            return retVal.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1> MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType.catalogInventoryStockRegistryV1GetStockStatusBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1 request) {
            return base.Channel.catalogInventoryStockRegistryV1GetStockStatusBySkuAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuResponse1> catalogInventoryStockRegistryV1GetStockStatusBySkuAsync(MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.CatalogInventoryStockRegistryV1GetStockStatusBySkuRequest catalogInventoryStockRegistryV1GetStockStatusBySkuRequest) {
            MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1 inValue = new MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest1();
            inValue.catalogInventoryStockRegistryV1GetStockStatusBySkuRequest = catalogInventoryStockRegistryV1GetStockStatusBySkuRequest;
            return ((MagentoAccess.Magento2catalogInventoryStockRegistryV1_v_2_0_2_0_CE.catalogInventoryStockRegistryV1PortType)(this)).catalogInventoryStockRegistryV1GetStockStatusBySkuAsync(inValue);
        }
    }
}
