//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class GenericFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors {
            get {
                return this.wrappedErrorsField;
            }
            set {
                this.wrappedErrorsField = value;
                this.RaisePropertyChanged("WrappedErrors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class GenericFaultParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class WrappedError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class FrameworkDataVideoContentInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mediaTypeField;
        
        private string videoProviderField;
        
        private string videoUrlField;
        
        private string videoTitleField;
        
        private string videoDescriptionField;
        
        private string videoMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
                this.RaisePropertyChanged("mediaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string videoProvider {
            get {
                return this.videoProviderField;
            }
            set {
                this.videoProviderField = value;
                this.RaisePropertyChanged("videoProvider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string videoUrl {
            get {
                return this.videoUrlField;
            }
            set {
                this.videoUrlField = value;
                this.RaisePropertyChanged("videoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string videoTitle {
            get {
                return this.videoTitleField;
            }
            set {
                this.videoTitleField = value;
                this.RaisePropertyChanged("videoTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string videoDescription {
            get {
                return this.videoDescriptionField;
            }
            set {
                this.videoDescriptionField = value;
                this.RaisePropertyChanged("videoDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string videoMetadata {
            get {
                return this.videoMetadataField;
            }
            set {
                this.videoMetadataField = value;
                this.RaisePropertyChanged("videoMetadata");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogDataProductAttributeMediaGalleryEntryExtensionInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrameworkDataVideoContentInterface videoContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkDataVideoContentInterface videoContent {
            get {
                return this.videoContentField;
            }
            set {
                this.videoContentField = value;
                this.RaisePropertyChanged("videoContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class FrameworkDataImageContentInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string base64EncodedDataField;
        
        private string typeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string base64EncodedData {
            get {
                return this.base64EncodedDataField;
            }
            set {
                this.base64EncodedDataField = value;
                this.RaisePropertyChanged("base64EncodedData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogDataProductAttributeMediaGalleryEntryInterface : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string mediaTypeField;
        
        private string labelField;
        
        private int positionField;
        
        private bool disabledField;
        
        private string[] typesField;
        
        private string fileField;
        
        private FrameworkDataImageContentInterface contentField;
        
        private CatalogDataProductAttributeMediaGalleryEntryExtensionInterface extensionAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
                this.RaisePropertyChanged("mediaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
                this.RaisePropertyChanged("label");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool disabled {
            get {
                return this.disabledField;
            }
            set {
                this.disabledField = value;
                this.RaisePropertyChanged("disabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
                this.RaisePropertyChanged("types");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
                this.RaisePropertyChanged("file");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public FrameworkDataImageContentInterface content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public CatalogDataProductAttributeMediaGalleryEntryExtensionInterface extensionAttributes {
            get {
                return this.extensionAttributesField;
            }
            set {
                this.extensionAttributesField = value;
                this.RaisePropertyChanged("extensionAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1GetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogDataProductAttributeMediaGalleryEntryInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public CatalogDataProductAttributeMediaGalleryEntryInterface result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1GetRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private int entryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int entryId {
            get {
                return this.entryIdField;
            }
            set {
                this.entryIdField = value;
                this.RaisePropertyChanged("entryId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1", ConfigurationName="Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProdu" +
        "ctAttributeMediaGalleryManagementV1PortType")]
    public interface catalogProductAttributeMediaGalleryManagementV1PortType {
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeMediaGalleryManagementV1Get is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Get", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.GenericFault), Action="catalogProductAttributeMediaGalleryManagementV1Get", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetResponse1 catalogProductAttributeMediaGalleryManagementV1Get(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Get", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetResponse1> catalogProductAttributeMediaGalleryManagementV1GetAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeMediaGalleryManagementV1Create is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Create", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.GenericFault), Action="catalogProductAttributeMediaGalleryManagementV1Create", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateResponse1 catalogProductAttributeMediaGalleryManagementV1Create(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Create", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateResponse1> catalogProductAttributeMediaGalleryManagementV1CreateAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeMediaGalleryManagementV1Update is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Update", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.GenericFault), Action="catalogProductAttributeMediaGalleryManagementV1Update", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateResponse1 catalogProductAttributeMediaGalleryManagementV1Update(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Update", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateResponse1> catalogProductAttributeMediaGalleryManagementV1UpdateAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeMediaGalleryManagementV1Remove is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Remove", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.GenericFault), Action="catalogProductAttributeMediaGalleryManagementV1Remove", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveResponse1 catalogProductAttributeMediaGalleryManagementV1Remove(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveResponse1> catalogProductAttributeMediaGalleryManagementV1RemoveAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1 request);
        
        // CODEGEN: Generating message contract since the operation catalogProductAttributeMediaGalleryManagementV1GetList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.GenericFault), Action="catalogProductAttributeMediaGalleryManagementV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListResponse1 catalogProductAttributeMediaGalleryManagementV1GetList(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="catalogProductAttributeMediaGalleryManagementV1GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListResponse1> catalogProductAttributeMediaGalleryManagementV1GetListAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1GetRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetRequest catalogProductAttributeMediaGalleryManagementV1GetRequest;
        
        public catalogProductAttributeMediaGalleryManagementV1GetRequest1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1GetRequest1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetRequest catalogProductAttributeMediaGalleryManagementV1GetRequest) {
            this.catalogProductAttributeMediaGalleryManagementV1GetRequest = catalogProductAttributeMediaGalleryManagementV1GetRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1GetResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetResponse catalogProductAttributeMediaGalleryManagementV1GetResponse;
        
        public catalogProductAttributeMediaGalleryManagementV1GetResponse1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1GetResponse1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetResponse catalogProductAttributeMediaGalleryManagementV1GetResponse) {
            this.catalogProductAttributeMediaGalleryManagementV1GetResponse = catalogProductAttributeMediaGalleryManagementV1GetResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1CreateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private CatalogDataProductAttributeMediaGalleryEntryInterface entryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CatalogDataProductAttributeMediaGalleryEntryInterface entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
                this.RaisePropertyChanged("entry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1CreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1CreateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1CreateRequest catalogProductAttributeMediaGalleryManagementV1CreateRequest;
        
        public catalogProductAttributeMediaGalleryManagementV1CreateRequest1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1CreateRequest1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1CreateRequest catalogProductAttributeMediaGalleryManagementV1CreateRequest) {
            this.catalogProductAttributeMediaGalleryManagementV1CreateRequest = catalogProductAttributeMediaGalleryManagementV1CreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1CreateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1CreateResponse catalogProductAttributeMediaGalleryManagementV1CreateResponse;
        
        public catalogProductAttributeMediaGalleryManagementV1CreateResponse1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1CreateResponse1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1CreateResponse catalogProductAttributeMediaGalleryManagementV1CreateResponse) {
            this.catalogProductAttributeMediaGalleryManagementV1CreateResponse = catalogProductAttributeMediaGalleryManagementV1CreateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1UpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private CatalogDataProductAttributeMediaGalleryEntryInterface entryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CatalogDataProductAttributeMediaGalleryEntryInterface entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
                this.RaisePropertyChanged("entry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1UpdateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1UpdateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1UpdateRequest catalogProductAttributeMediaGalleryManagementV1UpdateRequest;
        
        public catalogProductAttributeMediaGalleryManagementV1UpdateRequest1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1UpdateRequest1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1UpdateRequest catalogProductAttributeMediaGalleryManagementV1UpdateRequest) {
            this.catalogProductAttributeMediaGalleryManagementV1UpdateRequest = catalogProductAttributeMediaGalleryManagementV1UpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1UpdateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1UpdateResponse catalogProductAttributeMediaGalleryManagementV1UpdateResponse;
        
        public catalogProductAttributeMediaGalleryManagementV1UpdateResponse1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1UpdateResponse1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1UpdateResponse catalogProductAttributeMediaGalleryManagementV1UpdateResponse) {
            this.catalogProductAttributeMediaGalleryManagementV1UpdateResponse = catalogProductAttributeMediaGalleryManagementV1UpdateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1RemoveRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        private int entryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int entryId {
            get {
                return this.entryIdField;
            }
            set {
                this.entryIdField = value;
                this.RaisePropertyChanged("entryId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1RemoveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1RemoveRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1RemoveRequest catalogProductAttributeMediaGalleryManagementV1RemoveRequest;
        
        public catalogProductAttributeMediaGalleryManagementV1RemoveRequest1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1RemoveRequest1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1RemoveRequest catalogProductAttributeMediaGalleryManagementV1RemoveRequest) {
            this.catalogProductAttributeMediaGalleryManagementV1RemoveRequest = catalogProductAttributeMediaGalleryManagementV1RemoveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1RemoveResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1RemoveResponse catalogProductAttributeMediaGalleryManagementV1RemoveResponse;
        
        public catalogProductAttributeMediaGalleryManagementV1RemoveResponse1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1RemoveResponse1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1RemoveResponse catalogProductAttributeMediaGalleryManagementV1RemoveResponse) {
            this.catalogProductAttributeMediaGalleryManagementV1RemoveResponse = catalogProductAttributeMediaGalleryManagementV1RemoveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1GetListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("sku");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
        "AttributeMediaGalleryManagementV1")]
    public partial class CatalogProductAttributeMediaGalleryManagementV1GetListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogDataProductAttributeMediaGalleryEntryInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CatalogDataProductAttributeMediaGalleryEntryInterface[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1GetListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetListRequest catalogProductAttributeMediaGalleryManagementV1GetListRequest;
        
        public catalogProductAttributeMediaGalleryManagementV1GetListRequest1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1GetListRequest1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetListRequest catalogProductAttributeMediaGalleryManagementV1GetListRequest) {
            this.catalogProductAttributeMediaGalleryManagementV1GetListRequest = catalogProductAttributeMediaGalleryManagementV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class catalogProductAttributeMediaGalleryManagementV1GetListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://127.0.0.1:777/magento-2-1-0-0-ce/soap/default?services=catalogProduct" +
            "AttributeMediaGalleryManagementV1", Order=0)]
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetListResponse catalogProductAttributeMediaGalleryManagementV1GetListResponse;
        
        public catalogProductAttributeMediaGalleryManagementV1GetListResponse1() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1GetListResponse1(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetListResponse catalogProductAttributeMediaGalleryManagementV1GetListResponse) {
            this.catalogProductAttributeMediaGalleryManagementV1GetListResponse = catalogProductAttributeMediaGalleryManagementV1GetListResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface catalogProductAttributeMediaGalleryManagementV1PortTypeChannel : MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class catalogProductAttributeMediaGalleryManagementV1PortTypeClient : System.ServiceModel.ClientBase<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType>, MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType {
        
        public catalogProductAttributeMediaGalleryManagementV1PortTypeClient() {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public catalogProductAttributeMediaGalleryManagementV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetResponse1 MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1Get(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1Get(request);
        }
        
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetResponse catalogProductAttributeMediaGalleryManagementV1Get(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetRequest catalogProductAttributeMediaGalleryManagementV1GetRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1GetRequest = catalogProductAttributeMediaGalleryManagementV1GetRequest;
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetResponse1 retVal = ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1Get(inValue);
            return retVal.catalogProductAttributeMediaGalleryManagementV1GetResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetResponse1> MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1GetAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetResponse1> catalogProductAttributeMediaGalleryManagementV1GetAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetRequest catalogProductAttributeMediaGalleryManagementV1GetRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1GetRequest = catalogProductAttributeMediaGalleryManagementV1GetRequest;
            return ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateResponse1 MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1Create(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1Create(request);
        }
        
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1CreateResponse catalogProductAttributeMediaGalleryManagementV1Create(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1CreateRequest catalogProductAttributeMediaGalleryManagementV1CreateRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1CreateRequest = catalogProductAttributeMediaGalleryManagementV1CreateRequest;
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateResponse1 retVal = ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1Create(inValue);
            return retVal.catalogProductAttributeMediaGalleryManagementV1CreateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateResponse1> MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1CreateAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateResponse1> catalogProductAttributeMediaGalleryManagementV1CreateAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1CreateRequest catalogProductAttributeMediaGalleryManagementV1CreateRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1CreateRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1CreateRequest = catalogProductAttributeMediaGalleryManagementV1CreateRequest;
            return ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateResponse1 MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1Update(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1Update(request);
        }
        
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1UpdateResponse catalogProductAttributeMediaGalleryManagementV1Update(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1UpdateRequest catalogProductAttributeMediaGalleryManagementV1UpdateRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1UpdateRequest = catalogProductAttributeMediaGalleryManagementV1UpdateRequest;
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateResponse1 retVal = ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1Update(inValue);
            return retVal.catalogProductAttributeMediaGalleryManagementV1UpdateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateResponse1> MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1UpdateAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateResponse1> catalogProductAttributeMediaGalleryManagementV1UpdateAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1UpdateRequest catalogProductAttributeMediaGalleryManagementV1UpdateRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1UpdateRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1UpdateRequest = catalogProductAttributeMediaGalleryManagementV1UpdateRequest;
            return ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveResponse1 MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1Remove(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1Remove(request);
        }
        
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1RemoveResponse catalogProductAttributeMediaGalleryManagementV1Remove(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1RemoveRequest catalogProductAttributeMediaGalleryManagementV1RemoveRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1RemoveRequest = catalogProductAttributeMediaGalleryManagementV1RemoveRequest;
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveResponse1 retVal = ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1Remove(inValue);
            return retVal.catalogProductAttributeMediaGalleryManagementV1RemoveResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveResponse1> MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1RemoveAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveResponse1> catalogProductAttributeMediaGalleryManagementV1RemoveAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1RemoveRequest catalogProductAttributeMediaGalleryManagementV1RemoveRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1RemoveRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1RemoveRequest = catalogProductAttributeMediaGalleryManagementV1RemoveRequest;
            return ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1RemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListResponse1 MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1GetList(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1GetList(request);
        }
        
        public MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetListResponse catalogProductAttributeMediaGalleryManagementV1GetList(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetListRequest catalogProductAttributeMediaGalleryManagementV1GetListRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1GetListRequest = catalogProductAttributeMediaGalleryManagementV1GetListRequest;
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListResponse1 retVal = ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1GetList(inValue);
            return retVal.catalogProductAttributeMediaGalleryManagementV1GetListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListResponse1> MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType.catalogProductAttributeMediaGalleryManagementV1GetListAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1 request) {
            return base.Channel.catalogProductAttributeMediaGalleryManagementV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListResponse1> catalogProductAttributeMediaGalleryManagementV1GetListAsync(MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.CatalogProductAttributeMediaGalleryManagementV1GetListRequest catalogProductAttributeMediaGalleryManagementV1GetListRequest) {
            MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1 inValue = new MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1GetListRequest1();
            inValue.catalogProductAttributeMediaGalleryManagementV1GetListRequest = catalogProductAttributeMediaGalleryManagementV1GetListRequest;
            return ((MagentoAccess.Magento2catalogProductAttributeMediaGalleryManagementV1_v_2_1_0_0_CE.catalogProductAttributeMediaGalleryManagementV1PortType)(this)).catalogProductAttributeMediaGalleryManagementV1GetListAsync(inValue);
        }
    }
}
